# Generated by Django 3.1.5 on 2026-05-26 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('grid_emission_factor', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP', 'SAP ERP Fuel & Procurement'), ('UTILITY', 'Utility Billing Portal'), ('TRAVEL', 'Corporate Travel API')], max_length=20)),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('ingested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawIngestedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('raw_data_text', models.TextField()),
                ('status', models.CharField(choices=[('VALIDATED', 'Validated'), ('ERROR', 'Error'), ('SUSPICIOUS', 'Suspicious')], default='VALIDATED', max_length=20)),
                ('validation_errors', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='esg_ingest.ingestionjob')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedActivityRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('SCOPE_1', 'Scope 1 - Direct Emissions'), ('SCOPE_2', 'Scope 2 - Indirect Emissions'), ('SCOPE_3', 'Scope 3 - Value Chain Emissions')], max_length=20)),
                ('category', models.CharField(max_length=100)),
                ('activity_type', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('raw_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('normalized_unit', models.CharField(max_length=50)),
                ('co2e_kg', models.DecimalField(decimal_places=4, max_digits=15)),
                ('emission_factor_used', models.DecimalField(decimal_places=6, max_digits=12)),
                ('review_status', models.CharField(choices=[('PENDING_REVIEW', 'Pending Review'), ('SUSPICIOUS', 'Suspicious'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING_REVIEW', max_length=20)),
                ('suspicious_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('audit_seal_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_records', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='esg_ingest.facility')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='esg_ingest.organization')),
                ('raw_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='esg_ingest.rawingestedrecord')),
            ],
        ),
        migrations.AddField(
            model_name='ingestionjob',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='esg_ingest.organization'),
        ),
        migrations.AddField(
            model_name='facility',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='esg_ingest.organization'),
        ),
        migrations.CreateModel(
            name='AuditTrail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('EDIT', 'Modified'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('LOCK', 'Locked for Audit')], max_length=20)),
                ('changed_fields_text', models.TextField(blank=True, null=True)),
                ('change_reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('activity_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trails', to='esg_ingest.normalizedactivityrecord')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
